	PROGRAM AUTO_N
	IMPLICIT NONE
!
	INTEGER*4, PARAMETER :: NMAX=50
	REAL*8 G(NMAX)
	REAL*8 EDGE(NMAX)
	REAL*8 REC_LOW(NMAX)
	REAL*8 REC_HIGH(NMAX)
!
	REAL*8 AD_LOW(NMAX)
	REAL*8 AD_HIGH(NMAX)
!
	INTEGER*4 I,K
	REAL*8 HDKT,ION_EN
	REAL*8 LAM,ATOT,ATRANS
!
	CHARACTER*132 STRING
!
	CHARACTER*20 LEVEL(NMAX)
!
	HDKT=4.7994D0
	ION_EN=382704.0D0     !correct
	ION_EN=382644.0D0
!
	OPEN(UNIT=10,FILE='N4.dat',STATUS='OLD',ACTION='READ')
	  I=0
          DO WHILE(1 .EQ. 1)
            READ(10,'(A)',END=1000),STRING
	    DO WHILE(STRING .EQ. ' ' .OR. STRING(1:1) .EQ. '!')
	      WRITE(30,'(A)')STRING
              READ(10,'(A)',END=1000),STRING
	    END DO
	    K=INDEX(STRING,'  ')
	    I=I+1
            LEVEL(I)=STRING(1:K-1)
            READ(STRING(K:),*)G(I),EDGE(I),REC_LOW(I),REC_HIGH(I),LAM,ATOT,ATRANS
            EDGE(I)=(EDGE(I)-ION_EN)*2.99794D-05
            AD_LOW(I)=3.27296D-21*G(I)*EXP(-10.0*HDKT*EDGE(I))
            AD_LOW(I)=REC_LOW(I)/AD_LOW(I)
            AD_HIGH(I)=1.035D-22*G(I)*EXP(-HDKT*EDGE(I))
            AD_HIGH(I)=REC_HIGH(I)/AD_HIGH(I)
            WRITE(30,'(A,3ES14.3)')TRIM(STRING),AD_LOW(I),AD_HIGH(I),AD_LOW(I)*ATOT/ATRANS
          END DO
1000      CONTINUE
	CLOSE(UNIT=10)
!
	STOP
	END
